- name: intsall nginx
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: intsall nginx server
    ansible.builtin.package:
    name: nginx
    state: present

  - name: start nginx service
    ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes