- name: configure shipping component
  hosts: shipping
  become: yes
  tasks:
  #- name: configure shipping component
   # ansible.builtin.dnf:
    #  name: maven
     # state: present

  - name: install maven and mysql using loop
    ansible.builtin.dnf:
      name: "{{ item }}"
    loop:
    - maven
    - mysql

  - name: add roboshop user
    ansible.builtin.user:
      name: roboshop
      home: /app
      shell: /sbin/nologin
      system: true

  - name: create /app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: get code from gitmcommand: mv target/shipping-1.0.jar shipping.jar
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
      dest: /tmp/shipping.zip

  - name: unarchive the code
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes
  
  - name: install maven dependencies
    ansible.builtin.command: mvn clean packege
    args:
      chdir: /app

  - name: rename jar file
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
    args:
      chdir: /app

  - name: copy service file
    ansible.builtin.copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service

  - name: daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: start and enable shipping service
    ansible.builtin.service:
      name: shipping
      state: started
      enabled: yes

  - name: import mysql data
    community.mysql.mysql_db:
      name: all
      login_user: root
      login_password: RoboShop@1
      login_host: mysql.satish84s.site
      state: import
      target: "{{ item }}"
    loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql
    - /app/db/master-data.sql

    - name: restart shipping
      ansible.builtin.service:
        name: shipping
        state: restarted

        


  


  
